### ISSUE TITLE
Payload 2.0

### ISSUE THREAD

**Issue by samducker** [joas8211/payload-tenancy#24]
Hey I'm thinking about using this with the newly released payload 2.0 and postgres adapter is it compatible with either of those?

**Comment by joas8211** [comment]
I'll soon start working on upgrading the plugin to Payload 2.0, since I'll need this to work on my project also. Postgres is also a must for my project, so it will deinitiely be supported. Just give me some time, the Payload update just dropped :smile:

**Comment by samducker** [comment]
Yeah no pressure at all 😃. 

I just have a meeting later for a new project, and was just weighing up whether I should start with payload 2.0 or use one of the older versions.

As this plugin seems like an awesome concept for agencies hosting multiple projects for clients on one server. 

So thought I'd ask, but I'm in no rush, as haven't started using multi tenancy at all yet. 

I'll just start the new project as single tenant and upgrade later down the line. 

Whilst I've got you here I had a quick question, 

If I want to share some ui components / blocks between different tenants but not all of them. 

E.g. 

Client A - gets blocks 1 and 2 in their page builder.

Client B - gets 2 and 3 

2 is shared between both. 

Would I use globals to achieve this? 

I'm currently thinking to have a master project library on npm and import to each additional repo as needed.

**Comment by joas8211** [comment]
I've been stuck with the upgrade on extending edit view in Payload 2.0. It's needed for refreshing permissions during setup process. For anyone on Payload Discord server that has knowledge for the subject, help is needed.

https://discord.com/channels/967097582721572934/1160851828624338954/1160851828624338954

**Comment by mpresecan** [comment]
A simple fresh install by npx create-payload-app (mongoose adapter) and fresh install of tenency plugin brakes instalation

**Comment by joas8211** [comment]
Version 2.0.0 of this plugin has been now released! It supports (and requires) Payload 2.0.13.
