### ISSUE TITLE
Can't access any collections after installing

### ISSUE THREAD

**Issue by deitux123** [joas8211/payload-tenancy#37]
When a user opens any collection in the admin view (e.g. comments, posts, pages, etc), payload gives this error: 
```
QueryError: The following path cannot be queried: version.tenant
at validateQueryPaths (/home/node/app/node_modules/payload/src/database/queryValidation/validateQueryPaths.ts:91:13)
```

using:
```
    "payload": "^2.11.1",
    "payload-tenancy": "^2.1.1",
```

After some investigation, this seems to only happen on some collections, I'm using the payload seed project, and in collections that don't load there is this line:
```
  versions: {
    drafts: true,
  },
```

**Comment by andrewmota** [comment]
Hey @deitux123, how did you fix this problem?
