### ISSUE TITLE
Readme update to include install step

### ISSUE THREAD

**Issue by TatisLois** [joas8211/payload-tenancy#4]
The readme is great and figured that I should mention that I had to go back to discord to find the link to the package on NPM `https://www.npmjs.com/package/payload-tenancy`. I know it's a small detail but could be nice to include it with the install command in the readme directly. 

Willing to open a quick PR if it's helpful

**Comment by joas8211** [comment]
Thanks for raising the issue! I made some modifications to README. Hopefully it's more clear now :smiley:

**Comment by TatisLois** [comment]
Legend, thank you!
