### ISSUE TITLE
Possible bug: Slug field invalid format 

### ISSUE THREAD

**Issue by TatisLois** [joas8211/payload-tenancy#6]
I noticed that a slug can be saved in a invalid format for example `my slug`, ideally this would convert to `my-slug` for the user.

In other payload projects i've used this utils in a `beforeValidate` hook, what are your thoughts of including it into the project or a similar solution?

```
function formatSlug({ value }) {
  if (!value || typeof value !== "string") {
    return "";
  }

  return value
    .trim()
    .toLowerCase()
    .replace(/[^\w\s-]/g, "") // Remove non-word characters
    .replace(/\s+/g, "-") // Replace spaces with hyphens
    .replace(/--+/g, "-") // Replace multiple hyphens with a single hyphen
    .replace(/^-+|-+$/g, ""); // Remove leading/trailing hyphens
}
```

Alternatively is it possible to extend your tenancy collection to pass this in myself for the field?

**Comment by TatisLois** [comment]
I think we could add the beforeValidate to this file -> https://github.com/joas8211/payload-tenancy/blob/f687c556ab5518be52a3e732590136237943ed4d/src/fields/tenantSlug.ts

**Comment by TatisLois** [comment]
@joas8211 that would be perfect, currently I was trying to modify it in a `beforeOperation` or `beforeRead` hook on the collection but if you extended the config then that would make it much more powerful!

**Comment by joas8211** [comment]
Following issues are split from this issue: #11, #8. Closing this issue in favor or those split issues.
