### ISSUE TITLE
Extending field names and visibility 

### ISSUE THREAD

**Issue by TatisLois** [joas8211/payload-tenancy#7]
I had a simpler multi tenant application and so far this has been much more seamless, so thank you!

I had two questions though, let me know if it's possible to support. 

I am using a custom collection as the tenant ex: `tenantCollection: Business.slug` and noticed that the field still says tenant instead of the business name. I was wondering if it was possible to extend the configuration so that the relationship here could use another label? Also making it read only unless you are a user from the parent tenant could be handy too

<img width="500" alt="Screen Shot 2023-05-03 at 2 53 03 PM" src="https://user-images.githubusercontent.com/11730651/236032165-31836ac8-4116-4300-893e-d4fae028bf39.png">

Also is it possible to hide this field from the table view, when I visit it as an admin user or user from a parent tenant it shows up as undefined
<img width="1321" alt="Screen Shot 2023-05-03 at 2 47 31 PM" src="https://user-images.githubusercontent.com/11730651/236030724-b7730197-aa8a-45c6-8f1b-16193539775e.png">

When I view it was a user of the tenant it says no parent
<img width="1316" alt="Screen Shot 2023-05-03 at 2 51 26 PM" src="https://user-images.githubusercontent.com/11730651/236031638-5d2a51cc-2a21-4932-8cf9-7802b0efce9d.png">

hiding the column from this view would be great!

**Comment by TatisLois** [comment]
Again this is an awesome step up from trying to manage this myself with the various hooks, if there is no easy way to extend these option I can look into supporting through a PR as well :)

**Comment by TatisLois** [comment]
@joas8211 editing fields would definitely help here but having it as part of the tenant options would make it just as easy too. 

Alternatively if a user passes in a collection to be the tenant, I wonder if you could read the `useAsTitle` field and if it has a value then use that fields label. Not sure if that would work but could be a seamless way to support it

**Comment by joas8211** [comment]
Following issues are split from this issue: #8, #10, #9. Closing this issue in favor or those split issues.
